name: Docker Image CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: Production
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ashleegaf/face-detection

            - name: Set up Docker Buildx (CLI)
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  provenance: mode=max
                  sbom: true
                  push: ${{ github.event.name != 'pull-request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
