name: Docker Image CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: Production
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build Docker image and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  provenance: mode=max
                  sbom: true
                  push: ${{ github.event.name != 'pull-request' }}
                  tags: face-detection:${{ github.sha }}
